### ISSUE TITLE
Interface support and INI support

### ISSUE THREAD

**Issue by ghost1372** [Nucs/JsonSettings#5]
hi please add interface support for settings and ini format. like this library
https://github.com/aloneguid/config#declare-settings-interface

**Comment by Nucs** [comment]
Hey Mahdi,
I'll split my answer to two.
1. INI format: This will require to move rewrite the library and add abstraction layer to allow saving into an INI format because right now the library is "hardcoded" into using `Newtonsoft.Json`.
I do not have the time right now to do it but eventually I'll.
2. Regarding the interface implementation,
To what exactly do you refer? You can just create two settings classes that implement shared interface.

**Comment by ghost1372** [comment]
Yes you are right, I have not seen examples of your project tnx.
